destination: ../doc_outputs/mydoc/designers-pdf
url: "http://127.0.0.1:4010"
baseurl: "/mydoc/designers-pdf"
port: 4010
output: pdf
print_title: EXP Platform Documentation
print_subtitle: version 4.0
output: pdf
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page_print"
      comments: true
      search: true
